spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/PRESLY
    username: postgres
    password: Monze2020
    initialization-mode: always
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true